### ISSUE TITLE
Not issue, just question

### ISSUE THREAD

**Issue by kaeso** [blackarrowsec/redteam-research#11]
Hi. Do you have string for windows 2016?

`static const RPC_CLIENT_INTERFACE DefaultIfName___RpcClientInterface =
    {
    sizeof(RPC_CLIENT_INTERFACE),
    #if defined(WIN10)
    {{0xbe6293d3,0x2827,0x4dda,{0x80,0x57,0x85,0x88,0x24,0x01,0x24,0xc9}},{0,0}},
    #endif
    #if defined(WIN11)
    {{0xec029036,0x297f,0x4f3a,{0xa1,0x69,0x7a,0x2f,0xef,0xa5,0xcc,0x3e}},{0,0}},
    #endif
    #if defined(WIN2019)
    {{0xbe7f785e,0x0e3a,0x4ab7,{0x91,0xde,0x7e,0x46,0xe4,0x43,0xbe,0x29}},{0,0}},
    #endif
    #if defined(WIN2022)
    {{0xd8140e00,0x5c46,0x4ae6,{0x80,0xac,0x2f,0x9a,0x76,0xdf,0x22,0x4c}},{0,0}},
    #endif
    {{0x8A885D04,0x1CEB,0x11C9,{0x9F,0xE8,0x08,0x00,0x2B,0x10,0x48,0x60}},{2,0}},
    0,
    0,
    0,
    0,
    &DefaultIfName_ProxyInfo,
    0x02000000
    };
`

**Comment by Kudaes** [comment]
Hi @kaeso,

We do not have that UUID since we have not found Windows Server 2016 to be vulnerable to this bug. You can use RpcView in order to obtain that RPC interface UUID.
